src/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from core.views import ContactFormView


app_name = 'core'

urlpatterns = [
    url(r'^about/$',
        cache_page(60 * 15)(TemplateView.as_view(template_name='site/about.html')),
        name='about'),

    url(r'^contact-us/$',
        cache_page(60 * 15)(ContactFormView.as_view()),
        name='contact'),
]

src/equipments/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views.activity import ActivityDetailView
from .views.institution import (InstitutionPublicDetailView,
                                FavoriteInstitutions,
                                CommentedInstitutions,
                                EquipmentPublicDetailView,
                                InstitutionPhotoUploadView,
                                EquipmentPhotoUploadView)
from .views.search import SearchView

app_name = 'equipments'

urlpatterns = [

    url(r'activities/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$',
        ActivityDetailView.as_view(),
        name='activity-details'),

    url(r'institutions/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', InstitutionPublicDetailView.as_view(),
        name='institution-details'),

    url(r'equipments/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', EquipmentPublicDetailView.as_view(),
        name='equipment-details'),

    url(r'institutions/favorites/$', FavoriteInstitutions.as_view(), name='institutions-favorites'),
    url(r'institutions/commented/$', CommentedInstitutions.as_view(), name='institutions-commented'),

    url(r'search/$', SearchView.as_view(), name='search'),

    url(
        regex=r'^(?P<pk>\d+)/institution-upload/$',
        view=InstitutionPhotoUploadView.as_view(),
        name='institution_photo_upload_view',
    ),

    url(
        regex=r'^(?P<pk>\d+)/equipment-upload/$',
        view=EquipmentPhotoUploadView.as_view(),
        name='equipment_photo_upload_view',
    ),
]

src/equipments/models/activity.py
# -*- coding: utf-8 -*-
import random
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.core.urlresolvers import reverse

from colorfield.fields import ColorField

from utils.models.abstracts import (SluggedAbstractModel, DescribedAbstractModel,
                                    ActivatedAbstractModel, TimeStampedAbstractModel)


def generate_color():
    color = '#{:02x}{:02x}{:02x}'.format(*map(lambda x: random.randint(0, 255), range(3)))
    return color


@python_2_unicode_compatible
class Activity(SluggedAbstractModel, DescribedAbstractModel, ActivatedAbstractModel, TimeStampedAbstractModel):

    class Meta:
        verbose_name = _(u'Activité')
        verbose_name_plural = _(u'Activités')
        unique_together = ('label', 'slug',)
        ordering = ('label',)

    reference = models.IntegerField(_(u'reférence'), primary_key=True)
    image = models.ImageField(_(u'image'), null=True,)
    pin_color = ColorField(_(u'couleur du pin'), default=generate_color())

    def __str__(self):
        return self.label

    def get_absolute_url(self):
        return reverse('equipments:activity-details', kwargs={'pk': self.pk, 'slug': self.slug})

src/equipments/models/activity_level.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from utils.models.abstracts import SluggedAbstractModel, ActivatedAbstractModel, TimeStampedAbstractModel


@python_2_unicode_compatible
class ActivityLevel(SluggedAbstractModel, TimeStampedAbstractModel, ActivatedAbstractModel):

    class Meta:
        verbose_name = _(u'niveau de l\'activité')
        verbose_name_plural = _(u'niveaux des activités')
        ordering = ('label',)
        unique_together = ('label', 'slug')

    def __str__(self):
        return self.label

src/equipments/models/commune.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.db import models

from utils.models.abstracts import SluggedAbstractModel, ActivatedAbstractModel, TimeStampedAbstractModel
from equipments.models.department import Department


@python_2_unicode_compatible
class Commune(SluggedAbstractModel, TimeStampedAbstractModel, ActivatedAbstractModel):

    code_insee = models.CharField(_('code INSEE'), max_length=6, primary_key=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='communes', blank=True)

    class Meta:
        verbose_name = _(u'communes')
        verbose_name_plural = _(u'communes')
        ordering = ('label',)

    def __str__(self):
        return self.label

src/equipments/models/department.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.db import models

from utils.models.abstracts import SluggedAbstractModel, ActivatedAbstractModel, TimeStampedAbstractModel


@python_2_unicode_compatible
class Department(SluggedAbstractModel, TimeStampedAbstractModel, ActivatedAbstractModel):

    code = models.CharField(_('code département'), max_length=4, primary_key=True)

    class Meta:
        verbose_name = _(u'département')
        verbose_name_plural = _(u'départements')
        ordering = ('label',)
        unique_together = ('label', 'slug')

    def __str__(self):
        return self.label

src/equipments/models/discipline_sportive.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from django.db import models

from utils.models.abstracts import (SluggedAbstractModel, DescribedAbstractModel,
                                    ActivatedAbstractModel, TimeStampedAbstractModel)
from equipments.models.activity import Activity


@python_2_unicode_compatible
class SportDiscipline(SluggedAbstractModel, DescribedAbstractModel, ActivatedAbstractModel, TimeStampedAbstractModel):

    reference = models.PositiveIntegerField(_('reférence'), primary_key=True, default=0)
    activity = models.ForeignKey(
        Activity, on_delete=models.CASCADE, related_name='sports_disciplines', verbose_name=_('activité')
    )

    class Meta:
        verbose_name = _('discipline sportive')
        verbose_name_plural = _('disciplines sportives')
        unique_together = ('label', 'slug',)
        ordering = ('label',)

    @property
    def pin_color(self):
        if self.activity:
            return self.activity.pin_color
        return None

    def __str__(self):
        return self.label

src/equipments/models/equipment_category.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.db import models

from utils.models.abstracts import SluggedAbstractModel, ActivatedAbstractModel, TimeStampedAbstractModel
from equipments.models.equipment_category_family import EquipmentCategoryFamily


@python_2_unicode_compatible
class EquipmentCategory(SluggedAbstractModel, TimeStampedAbstractModel, ActivatedAbstractModel):

    family = models.ForeignKey(EquipmentCategoryFamily, on_delete=models.CASCADE, related_name='categories')

    class Meta:
        verbose_name = _(u'catégorie d\'équipements')
        verbose_name_plural = _(u'catégories d\'équipements')
        unique_together = ('label', 'slug',)
        ordering = ('label',)

    def __str__(self):
        return self.label

src/equipments/models/equipment_category_family.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from utils.models.abstracts import SluggedAbstractModel, ActivatedAbstractModel, TimeStampedAbstractModel


@python_2_unicode_compatible
class EquipmentCategoryFamily(SluggedAbstractModel, TimeStampedAbstractModel, ActivatedAbstractModel):

    class Meta:
        verbose_name = _('famille d\'équipements')
        verbose_name_plural = _('famille d\'équipements')
        unique_together = ('label', 'slug',)
        ordering = ('label',)

    def __str__(self):
        return self.label

src/equipments/models/equipment_target.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from utils.models.abstracts import SluggedAbstractModel, ActivatedAbstractModel, TimeStampedAbstractModel


@python_2_unicode_compatible
class EquipmentTarget(SluggedAbstractModel, TimeStampedAbstractModel, ActivatedAbstractModel):

    class Meta:
        verbose_name = _(u'publique cible')
        verbose_name_plural = _(u'publiques cibles')
        ordering = ('label',)
        unique_together = ('label', 'slug')

    def __str__(self):
        return self.label

src/equipments/forms/activity.py
# -*- coding: utf-8 -*-
from django import forms

from equipments.models.activity import Activity


class MultiSelectActivitiesForm(forms.Form):

    activities = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(),
                                                queryset=Activity.objects.filter(is_active=True).order_by('label'))


class MultiCheckboxActivitiesForm(forms.Form):

    activities = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(),
                                                queryset=Activity.objects.filter(is_active=True).order_by('label'))

src/equipments/views/activity.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView

from equipments.models.activity import Activity
from equipments.forms.activity import MultiSelectActivitiesForm


class ActivityListView(ListView):

    model = Activity
    template_name = 'equipments/partial/activities.html'

    paginate_by = 6

    def get_queryset(self):
        return Activity.objects.filter(is_active=True)

    def get_context_data(self, **kwargs):
        context = super(ActivityListView, self).get_context_data(**kwargs)
        context['form_activities'] = MultiSelectActivitiesForm
        return context


class ActivityDetailView(DetailView):

    model = Activity
    template_name = 'site/activity-detail.html'

src/equipments/views/institution.py
# -*- coding: utf-8 -*-
from django.views.generic import View

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, CreateView, ListView, UpdateView, DeleteView

# from equipments.forms.institution import InstitutionCreateForm
from equipments.models.equipment import Equipment
from equipments.models.institution import Institution
from equipments.models.activity import Activity
# from publishing.models.post import Post
from publishing.models.comment import Comment
from publishing.forms.comment import CreateCommentForm
from publishing.models.favorite import Favorite

from braces.views import (AjaxResponseMixin, JSONResponseMixin)

from utils.models.attachement import AttachedMedia


class InstitutionPhotoUploadView(JSONResponseMixin, AjaxResponseMixin, View):

    def post_ajax(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            error_dict = {'message': 'Only logged in users can upload files.'}
            return self.render_json_response(error_dict, status=401)
        try:
            institution = Institution.objects.get(pk=kwargs.get('pk'))
        except Institution.DoesNotExist:
            error_dict = {'message': 'Institution not found.'}
            return self.render_json_response(error_dict, status=404)
        uploaded_file = request.FILES['file']
        AttachedMedia.objects.create(
            image=uploaded_file,
            content_type=ContentType.objects.get_for_model(institution),
            object_id=institution.pk,
        )
        response_dict = {
            'message': 'File uploaded successfully!',
        }
        return self.render_json_response(response_dict, status=200)


class EquipmentPhotoUploadView(JSONResponseMixin, AjaxResponseMixin, View):

    def post_ajax(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            error_dict = {'message': 'Unauthorized.'}
            return self.render_json_response(error_dict, status=401)
        try:
            equipment = Equipment.objects.get(pk=kwargs.get('pk'))
        except Equipment.DoesNotExist:
            error_dict = {'message': 'Equipment not found.'}
            return self.render_json_response(error_dict, status=404)
        uploaded_file = request.FILES['file']
        AttachedMedia.objects.create(
            image=uploaded_file,
            content_type=ContentType.objects.get_for_model(equipment),
            object_id=equipment.pk,
        )
        response_dict = {
            'message': 'File uploaded successfully!',
        }
        return self.render_json_response(response_dict, status=200)


class EquipmentPublicDetailView(DetailView):

    model = Equipment
    template_name = 'equipments/equipment-public.html'

    def get_context_data(self, **kwargs):
        context = super(EquipmentPublicDetailView, self).get_context_data(**kwargs)
        context['form_comment'] = CreateCommentForm
        context['activities'] = Activity.objects.filter(sports_disciplines__equipments=context['equipment']).distinct()
        # context['activities'] = context['equipment'].disciplines.activity.distinct()
        return context

    @method_decorator(login_required)
    def post(self, request, pk, slug):
        # post = Post.objects.get(institution=self.get_object())
        obj = self.get_object()
        comment = Comment(
            publisher=request.user,
            content_type=ContentType.objects.get_for_model(obj),
            object_id=obj.pk,
        )
        comment_form = CreateCommentForm(request.POST, instance=comment)
        if comment_form.is_valid():
            comment_form.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return self.get_object().get_absolute_url()


class InstitutionPublicDetailView(DetailView):

    model = Institution
    template_name = 'equipments/institution-public.html'

    def get_context_data(self, **kwargs):
        context = super(InstitutionPublicDetailView, self).get_context_data(**kwargs)
        context['equipments'] = context['institution']\
            .equipments.filter(is_active=True, disciplines__is_active=True)\
            .distinct()
        context['form_comment'] = CreateCommentForm
        return context

    @method_decorator(login_required)
    def post(self, request, pk, slug):
        # post = Post.objects.get(institution=self.get_object())
        obj = self.get_object()
        comment = Comment(
            publisher=request.user,
            content_type=ContentType.objects.get_for_model(obj),
            object_id=obj.pk,
        )
        comment_form = CreateCommentForm(request.POST, instance=comment)
        if comment_form.is_valid():
            comment_form.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return self.get_object().get_absolute_url()


class FavoriteInstitutions(LoginRequiredMixin, ListView):

    model = Institution
    template_name = 'equipments/institutions-list.html'

    def get_queryset(self):
        # favorites = Favorite.objects.filter(publisher=self.request.user)
        return Institution.objects.filter(
            favorites__in=Favorite.objects.filter(publisher=self.request.user)
        ).distinct()


class CommentedInstitutions(LoginRequiredMixin, ListView):

    model = Institution
    template_name = 'equipments/institutions-list.html'

    def get_queryset(self):
        return Institution.objects.filter(
            comments__in=Comment.objects.filter(publisher=self.request.user, )
        ).distinct()

src/equipments/views/search.py
# -*- coding: utf-8 -*-
from django.shortcuts import redirect
from django.views.generic import TemplateView
from equipments.forms.activity import MultiCheckboxActivitiesForm
from equipments.models.activity import Activity


class SearchView(TemplateView):

    template_name = 'search/search.html'

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['form_activities'] = MultiCheckboxActivitiesForm
        return context

    def get(self, request, *args, **kwargs):
        if request.GET.get('previous') == '/':
            filters = dict(request.GET)
            if 'activities' in filters:
                activities = filters['activities']
                if len(activities) == 1:
                    activity = Activity.objects.get(reference=activities[0])
                    return redirect(activity.get_absolute_url())
        return super(SearchView, self).get(request, *args, **kwargs)

src/equipments/templates/site/activity-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ activity.label }}{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/range.css' %}">
    <link rel="stylesheet" href="{% static 'css/progressbar.css' %}">
    <link href='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.css' rel='stylesheet'/>
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css'
          rel='stylesheet'/>
    <!--[if lt IE 9]>
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.ie.css' rel='stylesheet' />
    <![endif]-->
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' rel='stylesheet'/>
{% endblock %}

{% block content %}
    <div class="progress-bar" id="progress-bar"></div>
    <header class="background-cover"
            style="background-image: url('{% if activity.image %}{{ activity.image.url }}{% else %}{% static 'img/placeholder@l.png' %}{% endif %}')">
    <div class="uk-overlay uk-light uk-container">
            <input name="activity-id" id="activityId" value="{{ activity.pk }}" hidden>
            <h1 class="uk-article-title">{{ activity.label }}</h1>
            {% if activity.description %}
            <h4>Description</h4>
                <p class="uk-text-justify">{{ activity.description }}</p>
            {% endif %}
        </div>
    </header>
    
    <section class="uk-container elements-details">
        <article class="uk-article">

            <form method="get" action="">

                <div class="uk-margin-bottom uk-width-1-1">
                    <input class="uk-input uk-margin-small-top" type="search" id="address-search"
                           placeholder="Rechercher un lieu..."/>
                </div>

                <div id="advanced-search" hidden>
                    <div class="uk-divider-icon"></div>
                    <div class="uk-margin-bottom uk-grid-small uk-child-width-1-2@s uk-grid" uk-grid>
                        <div class="uk-width-1-1">
                            <label><i>Type de lieu</i></label>
                        </div>

                        <label for="is_public"><input id="is_public" name="is_public" type="checkbox"
                                                      class="uk-checkbox"/> Public</label>
                        <label for="is_private"><input id="is_private" name="is_private" type="checkbox"
                                                       class="uk-checkbox"/> Privé</label>
                    </div>
                    <div class="uk-divider-icon"></div>
                    <div class="uk-margin-bottom uk-grid-small uk-child-width-1-2@s uk-grid" uk-grid>
                        <div class="uk-width-1-1">
                            <label><i>Disciplines spotives</i></label>
                        </div>
                        {% for discipline in activity.sports_disciplines.all %}
                            <label>
                                <input class="uk-checkbox"
                                       type="checkbox"
                                       name="disciplines"
                                       value="{{ discipline.pk }}"
                                       id="discipline_{{ discipline.pk }}">
                                {{ discipline.label }}
                            </label>
                        {% endfor %}
                    </div>
                    <div class="uk-divider-icon"></div>
                    <div class="uk-grid uk-child-width-1-2@s uk-padding-top" uk-grid>
                        <div class="uk-margin uk-width-1-1">
                            <div class="range-slider">
                                <label for="lat-search"><i>Distance de recherche (KM)</i></label>
                                <input class="range-slider__range" name="distance" id="distance-search"
                                       type="range" value="3" min="1" max="200">
                                <span class="range-slider__value">0</span>
                            </div>
                        </div>
                        <div class="uk-margin uk-hidden">
                            <label for="lng-search">Langitude</label>
                            <input class="uk-input uk-disabled" name="lng" type="search" id="lng-search"
                                   placeholder="Langitude"/>
                        </div>
                        <div class="uk-margin uk-hidden">
                            <label for="lat-search">Latitude</label>
                            <input class="uk-input uk-disabled" name="lat" type="search" id="lat-search"
                                   placeholder="Latitude"/>
                        </div>
                    </div>
                </div>

                <div class="uk-clearfix">
                    <div class="uk-float-right">
                        <button class="uk-button uk-button-default uk-margin-small-bottom"
                                uk-toggle="target: #advanced-search; animation: uk-animation-fade">recherche avancée
                        </button>
                        <input type="submit" value="Rechercher"
                               class="uk-button uk-button-primary uk-margin-small-bottom">
                    </div>
                </div>
            </form>
        </article>
    </section>

    <div class="black-separator"></div>

    <div class="uk-child-width-1-5 uk-grid-small uk-background-muted" data-sticky-container uk-grid>
        <div class="uk-container uk-width-3-5 map-elements-container" id="map-elements-container">
            <div class="uk-child-width-1-2@m uk-grid-small uk-grid-match map-elements" id="map-elements" uk-grid>
                <!-- -->
                <div class="uk-width-1-1">
                    <p>Merci de patienter</p>
                    <div class="spinner-container uk-background-muted">
                        <a class="infinite-more-link" href="#" style="display: block;"
                           uk-spinner></a>
                    </div>
                </div>
                <!-- -->
            </div>
        </div>
        <div class="uk-width-2-5 map-container sticky-map" id="map-container" data-sticky data-margin-top="80">
            <div id='map'></div>
        </div>
    </div>

    <div id="map-control">
        <a href="#" class="uk-icon-link" uk-icon="icon: chevron-right; ratio: 1.5" id="toggle-elements"></a>
        <a href="#" class="uk-icon-link" uk-icon="icon: chevron-left; ratio: 1.5" id="toggle-map"></a>
    </div>

    <div class="black-separator" id="bottom-scroll-spy"></div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.js'></script>
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

    <script async src="{% static 'js/range.js' %}"></script>

    <script async src="{% static 'js/institutions-map.js' %}"></script>
{% endblock %}

src/equipments/templates/site/home.html
{% extends 'base.html' %}
{% load static class_tags %}

{% block title %}Page d'accueil{% endblock %}

{% block styles %}
    {{ block.super }}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.4/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}
    <header class="hero uk-position-relative uk-visible-toggle uk-light" id="hero"
            uk-slideshow="autoplay: true; autoplay-interval: 4000; ratio: false">

        <ul class="uk-slideshow-items">
            <li><img data-src="{% static 'img/home/basket.png' %}" class="lazy" alt="basket" uk-cover></li>
            <li><img data-src="{% static 'img/home/football.png' %}" class="lazy" alt="football" uk-cover></li>
            <li><img data-src="{% static 'img/home/golf.png' %}" class="lazy" alt="golf" uk-cover></li>
            <li><img data-src="{% static 'img/home/tennis.png' %}" class="lazy" alt="tennis" uk-cover></li>
            <li><img data-src="{% static 'img/home/skate.png' %}" class="lazy" alt="skate" uk-cover></li>
            <li><img data-src="{% static 'img/home/badminton.png' %}" class="lazy" alt="badminton" uk-cover></li>
        </ul>

        <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#"
           uk-slidenav-previous uk-slideshow-item="previous"></a>
        <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#"
           uk-slidenav-next uk-slideshow-item="next"></a>

        <div class="uk-position-bottom uk-position-medium uk-text-center uk-light">

            <h1 class="uk-text-center" style="color: #f8f8f8">
                <i uk-icon="icon: search; ratio: 2"></i> Je cherche un terrain de
                <span class="txt-rotate"
                      data-period="2000"
                      data-rotate='[ "Basket", "Football", "Golf", "Tennis", "Skate" , "Badminton" ]'></span>
            </h1>
            <a href="#activities" class="uk-align-center uk-button uk-width-1-2@s button-orange"
               uk-scroll="offset:80">
                <span class="uk-margin-small-right" uk-icon="icon: thumbnails"></span>
                Afficher toutes les activités
            </a>
        </div>
    </header>

    <div class="black-separator"></div>

    {% include 'equipments/partial/activities.html' %}
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/waypoints@4.0.1/lib/jquery.waypoints.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/waypoints@4.0.1/lib/shortcuts/infinite.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.4/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lazyload@2.0.0-beta.2/lazyload.js"></script>
    <script>
        
            window.addEventListener("load", function(){
                window.cookieconsent.initialise({
                  "palette": {
                    "popup": {
                      "background": "#eaf7f7",
                      "text": "#5c7291"
                    },
                    "button": {
                      "background": "#56cbdb",
                      "text": "#ffffff"
                    }
                  },
                  "content": {
                    "message": "Ce site utilise des cookies pour vous assurer la meilleure expérience sur notre site.",
                    "dismiss": "Je comprend",
                    "link": "En savoir plus",
                    "href": "https://www.kojump.fr/legal/privacy-policy/"
                  }
                })});
                
        // Lazy loading images slider
        var images = document.querySelectorAll(".lazy");
        var lazy = new lazyload(images);
        lazy.loadImages();

        $(document).ready(function() {
            var infinite = new Waypoint.Infinite({
                element: $('.infinite-container')[0],
                onBeforePageLoad: function () {
                    $('.infinite-more-link').show();
                },
                onAfterPageLoad: function ($items) {
                    $('.infinite-more-link').hide();
                }
            });
        });

        $('#id_activities').select2();
    </script>
{% endblock %}